require_relative 'lib/configure_repos'

desc "Configure the repos with correct settings and branch protection"
task :configure_repos do
  ConfigureRepos.new.configure!
end

desc "Remove old webhooks"
task :remove_old_webhooks do
  HOOKS_TO_DELETE = %w[
    https://snyk.io/webhook/github
  ]

  repos.map do |repo|
    client.hooks(repo).each do |hook|
      next unless HOOKS_TO_DELETE.include?(hook.config.url)
      client.remove_hook(repo, hook.id)
    end
  end
end
